### PR TITLE
Splitting on something that is not part of a string will not work

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by kapilpau** [comment]
Hi @XanderAtBackboneSystems,

Thank you for contributing. I am confused about what this PR is trying to achieve. It is good practice to explain in the description what the change is doing and why you are making the change. Also, if you wish to remove code, please delete it. It is poor practice to commit commented out code, without having a comment to justify it. If it is not needed, then simply delete it.

Please explain what you're hoping this change will achieve, I am struggling to see the purpose of it.

**Comment by ghost** [comment]
hi @kapilpau ,

Sorry that my initial PR was a bit confusing... Hopefully a meaningful explanation

The code (line 245-254) checks whether the string containing the path ends with the same string as was found in module line of the go.mod file. If not (as is in my case) the code tries to split the path with the module name as separator. In my case the module name is not completely part of my path and thus the split will yield a slice of one element containing the complete path. Then the code assumes there are at least two element and returns the 2nd element. The result is the following panic:

```
$ go-mod-dependency-tree .
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
main.getModuleName({0xc000016054, 0x0})
	/Users/<someuser>/go/src/github.com/kapilpau/go-mod-dependency-tree/dependency-tree.go:251 +0x345
main.main()
	/Users/<someuser>/go/src/github.com/kapilpau/go-mod-dependency-tree/dependency-tree.go:74 +0x496
```

To fix the code so it worked for me i choose to keep the module name as it was found in the `go.mod` file and left the path on its own. 

I only commented the lines as i have no idea why the code does this (i have no knowledge to make the call whether this is right or wrong and what is allowed or not) . Therefore i only commented the lines. And come to think of it; maybe my pull request was more of a pointer to were i have an issue with the code than as an actual solution.

I can easily provide you a working solution without commented code. But i am not sure whether that would be the complete and an appropriate solution. 

Can you elaborate why the code on line 145-154 was coding the way it was. The interesting part is in the below snippet.

```
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, "module ") {
			modAddress := strings.Split(line, "module ")[1]
			var modName string
			if strings.HasSuffix(cwd, modAddress) {
				modName = modAddress
			} else {
				modName = modAddress + strings.Split(cwd, modAddress)[1]
			}
			return modName
		}
```

Hope i can help some more... 

Best regards,

Xander

**Comment by kapilpau** [comment]
@XanderAtBackboneSystems I have managed to replicate this issue now, thanks for the details. The issue occurred when the module name had quotes around it, in its own go.mod (which is optional). I have fixed this issue and released a new version (v1.2.1). Please try using that and let me know if that has fixed it.

As you mentioned in your comment, this was to alert me of a bug. In the future, please create an issue to do so, rather than a PR, or investigate and resolve the issue in your PR (don't just comment out the code).

If the bug has been fixed, please let me know and then close this PR. Thanks

**Comment by ghost** [comment]
Hi @kapilpau ,

The quotes are not my problem. Good catch though

My case it following:

In my go.mod file i have:
```
module github.com/some-owner/some-project
```

And the directory in my computer in which the repo is cloned:
```
~/source-code/some-project
```
(this is also the directory that contains my `go.mod` file)

I run the tool without any arguments and the working directory is the same is `~/source-code/some-project`.

`modAddress` =  `github.com/some-owner/some-project`
`cwd` = `/<obsolute-path-user-dir>/source-code/some-project`

```
if strings.HasSuffix(cwd, modAddress) { // will be false
        modName = modAddress
    } else {
        // will fail as modAddress is not part of the cwd and thus an slice is returned with only one element
        modName = modAddress + strings.Split(cwd, modAddress)[1]
}
```

If you like i can remove all commented lines from the pr and re submit it.

best regards.

**Comment by kapilpau** [comment]
I see, then your problem is you're breaking the Go directory structure. This tool expects your code to `~/go/src/github.com/<username>/<repo_name>` which is how Go sets it up

**Comment by ghost** [comment]
In the old `GOPATH` situation this was mandatory but since modern versions of go (due to go modules) this is no longer necessary by go. A good example on how i would do it is [here](https://www.wolfe.id.au/2020/03/10/starting-a-go-project/). So i am wondering why a tool like this would enforce this.

**Comment by ghost** [comment]
If you do not wish to pursue my case i will abandon this PR. I wil then not be able to use your tool but thats my problem

**Comment by kapilpau** [comment]
@XanderAtBackboneSystems this is not an actively maintained library, as I have a day job and other projects which have a higher priority. This tool works as intended, however, your scenario is an edge case that hadn't previously been encountered or considered. As such, this is not something I am likely to get round to doing, especially as I would have to reconfigure my local environment to be able to replicate yours, and that's something I have no desire to do. If you wish to use this tool with your set up, please try and contribute a fix that enables it to run for you, without just commenting out or deleting lines of code. Either way, this PR should be closed and a new one should be opened when you're ready to contribute the fix.

**Comment by ghost** [comment]
To be able to contribute i would need answers to above questions. The most important one being why you would have the if stament that went wrong (note that in my opinion the code did not do what was expected). I can not deduct what was intended. So i can fix it. 

I did change the PR to not have commented code, so if your main concern is the wrong way i started the PR then sorry. I'm really wanting the contribute, but i need some help as to why it was like it was. If your not able then that is a shame and i will close the PR.

**Pull request closed without merging**
